### ISSUE TITLE
Add a way to set the seed of the random number generator

### ISSUE THREAD

**Issue by metareven** [njanor/Navnegenerator#1]
I am currently using this project to generate random people for a test-project, but unfortunately I am not able to set the seed of the random number generator for Navnegenerator meaning that I am unable to reproduce the same test data between test runs.

Could you add a way to lock the seed so that I am able to generate the same random names between each test-run?

**Comment by njanor** [comment]
Sorry, did not get a notification about this. I'll have a look at it this evening 👍

**Comment by njanor** [comment]
Package version 1.1.0 should resolve this 👍
